version: "3.9"

services:
  backend:
    image: mahesh1925/lms-backend:latest
    container_name: lms-backend
    ports:
      - "8000:8000"
    env_file:
      - ${BACKEND_ENV}
    restart: always
    networks:
      - lms-network

  frontend:
    image: mahesh1925/lms-frontend:latest
    container_name: lms-frontend
    ports:
      - "8082:80"
    env_file:
      - ${FRONTEND_ENV}
    depends_on:
      - backend
    restart: always
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

