version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: lms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lms-network
    restart: always

  backend:
    image: mahesh1925/lms-backend:latest
    container_name: lms-backend
    ports:
      - "8000:8000"
    env_file:
      - ${BACKEND_ENV}
    depends_on:
      - mongodb
    networks:
      - lms-network
    restart: always

  frontend:
    image: mahesh1925/lms-frontend:latest
    container_name: lms-frontend
    ports:
      - "8082:80"
    env_file:
      - ${FRONTEND_ENV}
    depends_on:
      - backend
    networks:
      - lms-network
    restart: always

networks:
  lms-network:
    driver: bridge

volumes:
  mongo-data:

